### ISSUE TITLE
Colorize output

### ISSUE THREAD

**Issue by rogovdm** [typicode/hotel#196]
Is it possible to respect colors in console output?

**Comment by bamtron5** [comment]
I'm stuck in the web UI because log output gets some odd messaging due to a few concurrent tasks

`tsc && concurrently -r \"nodemon\" \"webpack --config webpack/webpack.config.js -w\" \"node-sass client/styles/ -o client/styles/ -w\""`

**Comment by danielpa9708** [comment]
I get this output in linux
![image](https://user-images.githubusercontent.com/17787042/34893630-1a0c4548-f7ac-11e7-8510-85a721f806ee.png)

**Comment by adius** [comment]
Why was this closed?

**Comment by adius** [comment]
@typicode Can you please make a comment what's the state of this?
At the moment at output looks really bad.

<img width="835" alt="screen shot 2018-01-21 at 18 31 51" src="https://user-images.githubusercontent.com/969983/35197592-692d032c-fed9-11e7-8b36-88c22f992957.png">

`&nbsp;`, no color, color formatting code `<span style=…`

Is there another issue, is something blocking, do you need help?

**Comment by typicode** [comment]
Thanks for the heads up, it's a bug. Probably due to the refactor.

It worked in Vue:
https://github.com/typicode/hotel/blob/v0.7.6/src/front/App.vue#L167-L169

And I think the reason is because the order isn't correct here:
https://github.com/typicode/hotel/blob/master/src/app/formatter.ts#L13-L15

cc @houfio if you reorder filters, is it better?
