### ISSUE TITLE
Styling within console output 

### ISSUE THREAD

**Issue by xanatas** [typicode/hotel#266]
Hi in previous hotel versions this worked but now the console gives this for example:

`<span style="color:blue">I20180123-15:48:24.597(1)? </span>`

Maybe its a setting but it makes console output unreadable for some things.
Any tip?

Thanks for taking the time to maintain this little app its great!

**Comment by houfio** [comment]
Well, that's interesting. [It was my pr](https://github.com/typicode/hotel/pull/265) that broke this, but what it was trying to do was fix this very issue.
Are you sure this worked in 0.8.4? Because for other people, [it was broken in that version too](https://github.com/typicode/hotel/issues/196#issuecomment-359269591).
Could you please make a repo with the issue so I can take a look at it?

**Comment by xanatas** [comment]
Hey no sorry the previous version i had was 0.7. something.
I did not know this error was introduced in 0.8.4.

**Comment by houfio** [comment]
It was introduced in 0.8, but the latest release (0.8.5) was an attempt to fix this. Do you still have this issue in that version?

**Comment by xanatas** [comment]
updated from 0.8.4 to 0.8.5

FIXED!
THANKS!
