### ISSUE TITLE
Internet unreachable with proxy-pac-with-proxy.pug 

### ISSUE THREAD

**Issue by nchudleigh** [typicode/hotel#278]
Ran into an issue with my set up where I had to copy proxy-pac.pug's content to proxy-pac-with-proxy.pug in order for the internet to be reachable again.

I don't have any insight into why this doesnt work and why this fix works.  But it do.

**Comment by nchudleigh** [comment]
![image](https://user-images.githubusercontent.com/5580824/36500723-114e6694-1713-11e8-99f8-5a0c35a0303d.png)

![image](https://user-images.githubusercontent.com/5580824/36500745-26bbb9f0-1713-11e8-967a-a588dcb8e9c8.png)

**Comment by typicode** [comment]
Hi @nchudleigh,

Sorry for the doc, it may be unclear. If you have a company network proxy, you should put its address or leave `false` otherwise (`true` is probably what's making it fail):
https://github.com/typicode/hotel/blob/master/src/conf.js#L14-L16

So here, if you don't have an existing network proxy, simply remove `"proxy": true" line and restart `hotel stop && hotel start`.

On a side note, in recent versions, Hotel will use default values if they're not present in `~/.hotel/conf.json`. So if you only want to change the `tld`, your conf could look like this:

```json
{
  "tld": "deb"
}
```

Let me know if it helps.

**Comment by nchudleigh** [comment]
That helps a lot will give that a shot, thanks.
