### ISSUE TITLE
Funding Hotel, looking for your feedback

### ISSUE THREAD

**Issue by typicode** [typicode/hotel#280]
Hi all 👋

I’m currently looking for ways and ideas to help me spend more time on Hotel.
Funding Hotel development would allow:

* Improved features and new functionalities
* Better support with faster replies and PR reviews on GitHub
* More frequent releases

I'd love to have your feedback about what would be the best approach and your usage of Hotel.

If you have some time, I've created a Google form here: 
__https://goo.gl/forms/EmgJVn2wzhRHAGYk1__

PS: at the end, you'll find an area for all comments.

Thank you! 🙏

**Comment by likun7981** [comment]
- `hotel domain`  A command configures proxy, and now I have implemented Mac, not compatible with __linux__ and __windows__.
- `hotel config` Open the `conf.json` file,  otherwise I need to find this file every time.
[launchEditor](https://github.com/facebook/create-react-app/blob/next/packages/react-dev-utils/launchEditor.js) can do it
- Other, watch the config file, If the configuration file changes, restart service and refresh network automatically.

**Comment by typicode** [comment]
Huge thanks to everyone who has answered, it was super helpful! So I went with a Patreon page and a  [Thanks](https://thanks.typicode.com/) page that my projects README will link to.

Thanks @likun7981 for the ideas 👍
