### ISSUE TITLE
run multiple servers for one app

### ISSUE THREAD

**Issue by samjbmason** [typicode/hotel#33]
I have a rails app that uses react on the frontend, I normally have to spin up one terminal tab with `rails s` and then in another tab run `gulp` to spin up my front end build task which also sets up a server for hot reloading and i use that url, is tis possible with hotel?

**Comment by typicode** [comment]
You can't "group" servers. But you can add both:

```
my-project$ hotel add -n rails-server -p 3000 'rails server --port $PORT'
my-project$ hotel add -n gulp-server 'gulp server'
```

Use `-n` if you start servers from the same directory to distinguish them.

If you're not using `.dev` domains, you may want to set fixed port so that `rails` is always available under the same address.

You may need to set a fixed port as well for gulp hot reload server (like `1337` if you're using `gulp-hot-reload`), but I'm not sure about that.

**Comment by k9ordon** [comment]
:(

**Comment by typicode** [comment]
Just some new thoughts about it, you could also group your servers using a `Procfile` or have them all in the `start` script of your `package.json` (`cmd1 & cmd2 & wait` on OSX and Linux).

**Comment by MatthiasWinkelmann** [comment]
I added a rails server as a prestart script to` package.json` as such: 
`"prestart": "../bin/rails server -p 3000 -d"`
The `-p` is necessary as otherwise the node and rails servers would try to use the same port.
