### ISSUE TITLE
Option for specifying bind IP

### ISSUE THREAD

**Issue by jsierles** [typicode/hotel#4]
Listening on localhost means we can't use xip.io. Would this be a reasonable PR?

**Comment by typicode** [comment]
You're right, I've added the option.

`~/.hotel/conf.json`

```json
{
  "port": 2000,
  "host": "0.0.0.0"
}
```

However, it won't work with xip.io because the daemon doesn't check the hostname to find the process (`name.192.168.x.y.xip.io`).

But, if you need to access a server from another device, you can use the following URL:

```bash
http://192.168.x.y:2000/name # -> will redirect to http://192.168.x.y:4567`
```

Or you can symply go to `http://192.168.x.y:2000` and get server list.

**Comment by jsierles** [comment]
Thanks! I thought xip.io would still work by doing:
http://192.168.x.y.xip.io:2000/name

**Comment by typicode** [comment]
You're welcome.

BTW the URL in your example should work, it's only "sub-domains" on xip.io (i.e. `name.a.b.c.d.xip.io`) that won't.
