### ISSUE TITLE
Offline *.dev support

### ISSUE THREAD

**Issue by davej** [typicode/hotel#57]
On OS X it doesn't seem possible to apply an automatic proxy conf url when offline because you can only apply a proxy to an interface (e.g. WiFi). Any thoughts on this?

**Comment by typicode** [comment]
Yes :) you have 2 options:

Configure your browser to use hotel's proxy directly: https://github.com/typicode/hotel/blob/master/docs/README.md

Use localhost:2000/my-app (and if you're bothered by the random port, remember you can set a fixed port when adding your project).

There may be some issues with icons on localhost:2000 since it loads font awesome icons from a CDN (PR welcome).

**Comment by typicode** [comment]
Added #58

**Comment by davej** [comment]
I don't Chrome supports setting a proxy directly it seems to just use the system-level settings (on OS X anyway). Thanks for your help though. :-)

**Comment by typicode** [comment]
You're welcome :)

Regarding Chrome, you can't do it from the settings in the GUI but you can actually pass a proxy from the command line:

```
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --proxy-pac-url=http://localhost:2000/proxy.pac
```

You need to quit Chrome before though.
