### ISSUE TITLE
more options for start?

### ISSUE THREAD

**Issue by floydwch** [typicode/hotel#66]
The app server started from accessing the URL provided by hotel. However, the start could be slow, and wait the time during start is less productive.

It would be nice to have more start options such as `hotel start myapp` and `hotel start --all` to start the app server actively.

**Comment by typicode** [comment]
To keep things simple, for the moment I prefer to limit the number of ways to do things. Since you can already start servers from the user interface or simply by making a request to `project.dev`, I feel it would be redundant to add an option to the CLI. Sorry.

As a workaround though, you can use `curl` or create a start script:

```sh
# start.sh
curl http://localhost:2000/project-1
curl http://localhost:2000/project-2
# or
curl project-1.dev
...
```

```sh
sh start.sh
```

**Comment by floydwch** [comment]
Hmm, it's ok. Thanks for your suggestion.
