### ISSUE TITLE
Reconsider the use of scripts.install

### ISSUE THREAD

**Issue by rstacruz** [typicode/hotel#8]
Using `scripts.install` is not considered a good practice and may lead to strange side effects. Consider instead having users run `hotel autostart` themselves.

`npm help scripts` has this to say about _install_:

> Don't  use  install.  Use a .gyp file for compilation, and prepublish for anything else. You should almost never have to explicitly set a preinstall or install script. If you are  doing  this,  please  consider  if  there is another option. The only valid use of install or preinstall scripts is for compilation which must be done on the target architecture.

You will notice that when working on `hotel` in development, this makes for some strange behavior too:

```
→  npm install

> ws@0.5.0 install ...
> (node-gyp rebuild 2> builderror.log) || (exit 0)

> ws@0.4.31 install ...
> (node-gyp rebuild 2> builderror.log) || (exit 0)

> fsevents@0.3.6 install ...

> hotel@0.2.10 install ...
> node bin/install

module.js:334
    throw err;
          ^
Error: Cannot find module '../lib/actions/autostart'
```

This is because running `npm install` (for development) will run scripts.install _then_ scripts.prepublish.

Consider instead having something like:

```js
scripts: {
  install: "echo; echo Hotel is now installed.; echo Run 'hotel autostart' and visit 'http://localhost:2000' to get started.; echo"
}
```

**Comment by veggiemonk** [comment]
+1 took me a while to figure out what was going on.

**Comment by typicode** [comment]
I've read about that. But I'm a bit unsure, need to think about it.

Strictly from a user point of view, I think it's not so bad. Mainly because, you don't have to manually run `hotel autostart && hotel start` every time you update/install the project. You just install `hotel` and you're good to go.

On the other side, it's clearly annoying as a contributor.

But, there's case where you can also do cool stuff using install scripts like automatically install git hooks [husky](https://github.com/typicode/husky). 

In any case, I'll fix the issue when running `npm install` in the project directory.
I plan to make a release this week or the next week.

**Comment by rstacruz** [comment]
There's also the caveat for users in doing `npm install hotel` (without -g) and hotel will add in an autostart entry which will probably break.

**Comment by typicode** [comment]
`v0.3` doesn't use `scripts.install` to start daemon anymore.
